/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EnableZigbee2MqttDebugLogs = boolean;
export type EnableAdapterDebugLogs = boolean;
export type HostnameOfTheMqttBrokerEGLocalhost = string;
export type PortOfTheMqttBrokerDefault1883 = number;
export type TopicPrefixOfTheAdapterDefaultZigbee2Mqtt = string;
export type Username = string;
export type Password = string;
export type ListOfZigbee2MQTTAdapters = Zigbee2MQTTAdapter[];

export interface Config {
  zigbee2mqttDebugLogs?: EnableZigbee2MqttDebugLogs;
  adapterDebugLogs?: EnableAdapterDebugLogs;
  zigbee2mqttAdapters?: ListOfZigbee2MQTTAdapters;
  [k: string]: unknown;
}
export interface Zigbee2MQTTAdapter {
  host: HostnameOfTheMqttBrokerEGLocalhost;
  port?: PortOfTheMqttBrokerDefault1883;
  topicPrefix?: TopicPrefixOfTheAdapterDefaultZigbee2Mqtt;
  username?: Username;
  password?: Password;
  [k: string]: unknown;
}
